
spring:
  cloud:
    stream:
      kafka:
        bindings:
          csv:
            destination: csv-topic
            content-type: text/plain
            group: csv-group
          csv-to-json:
            destination: json-topic
            content-type: application/json
          xml:
            destination: xml-topic
            content-type: text/plain
            group: xml-group
          xml-to-json:
            destination: json-topic
            content-type: application/json
        binder:
          deserializationExceptionHandler: sendToDlq
          transaction:
            producer:
              partition-count: 5
              compression-type: snappy